'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import {
  BookOpen,
  CalendarClock,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  RotateCcw,
  Settings2,
  Sparkles,
  SkipForward,
  Target,
  Trash2,
} from 'lucide-react';
import {
  STUDY_SESSION_STATUS_LABELS,
  WEEKDAY_SHORT_LABELS,
  type StudySessionItem,
} from '@painel/shared';
import {
  useAvailability,
  useCompleteStudySession,
  useDeleteStudySession,
  useReopenStudySession,
  useSkipStudySession,
  useStudyPlanSummary,
  useStudySessions,
} from '@/hooks/use-study-plan';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { EmptyState } from '@/components/empty-state';
import { AvailabilityDialog } from '@/components/schedule/availability-dialog';
import { GeneratePlanDialog } from '@/components/schedule/generate-plan-dialog';
import { formatDate, formatTime } from '@/lib/format';

const DAY = 24 * 60 * 60 * 1000;

/** Segunda-feira da semana da data informada. */
function startOfWeek(date: Date): Date {
  const result = new Date(date);
  // getDay(): 0 = domingo. Deslocamos para que a semana comece na segunda.
  const offset = (result.getDay() + 6) % 7;

  result.setDate(result.getDate() - offset);
  result.setHours(0, 0, 0, 0);

  return result;
}

function formatMinutes(minutes: number): string {
  if (minutes < 60) return `${minutes}min`;

  const hours = Math.floor(minutes / 60);
  const rest = minutes % 60;

  return rest === 0 ? `${hours}h` : `${hours}h ${rest}min`;
}

const STATUS_VARIANT = {
  PLANNED: 'secondary',
  IN_PROGRESS: 'pending',
  COMPLETED: 'completed',
  SKIPPED: 'overdue',
} as const;

function SessionRow({
  session,
  onComplete,
  onSkip,
  onReopen,
  onDelete,
}: {
  session: StudySessionItem;
  onComplete: (session: StudySessionItem) => void;
  onSkip: (session: StudySessionItem) => void;
  onReopen: (session: StudySessionItem) => void;
  onDelete: (session: StudySessionItem) => void;
}) {
  const isDecided = session.status === 'COMPLETED' || session.status === 'SKIPPED';
  const color = session.subject?.color ?? 'var(--color-muted-foreground)';

  return (
    <Card
      /* `flex-row` explicito: o Card traz `flex-col` por padrao, e sem isto os
         botoes de acao caem para baixo do conteudo em vez de ficarem a direita. */
      className={`flex min-w-0 flex-row items-start gap-3 p-3 ${isDecided ? 'opacity-70' : ''}`}
      data-testid="session-row"
    >
      <span
        className="mt-1 h-10 w-1 shrink-0 rounded-full"
        style={{ backgroundColor: color }}
        aria-hidden
      />

      <div className="min-w-0 flex-1">
        <p className="line-clamp-2 text-sm font-medium">{session.title}</p>

        <p className="mt-0.5 text-xs text-muted-foreground">
          {formatTime(session.scheduledStart)} — {formatTime(session.scheduledEnd)} ·{' '}
          {formatMinutes(session.plannedMinutes)}
          {session.actualMinutes !== null &&
            session.actualMinutes !== session.plannedMinutes &&
            ` · ${formatMinutes(session.actualMinutes)} estudados`}
        </p>

        <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
          <Badge variant={STATUS_VARIANT[session.status]}>
            {STUDY_SESSION_STATUS_LABELS[session.status]}
          </Badge>

          {session.subject && <Badge variant="outline">{session.subject.name}</Badge>}

          {!session.autoGenerated && <Badge variant="outline">Seu</Badge>}

          {session.examPrepId && (
            <Link href={`/plano-de-estudos/${session.examPrepId}`}>
              <Badge
                variant="outline"
                className="gap-1 text-muted-foreground hover:text-foreground"
              >
                <BookOpen className="size-3" aria-hidden />
                Do plano
              </Badge>
            </Link>
          )}
        </div>
      </div>

      <div className="flex shrink-0 gap-1">
        {isDecided ? (
          <Button
            variant="ghost"
            size="icon"
            className="size-8"
            aria-label={`Reabrir ${session.title}`}
            onClick={() => onReopen(session)}
          >
            <RotateCcw className="size-4" aria-hidden />
          </Button>
        ) : (
          <>
            <Button
              variant="ghost"
              size="icon"
              className="size-8 text-status-completed"
              aria-label={`Concluir ${session.title}`}
              onClick={() => onComplete(session)}
            >
              <Check className="size-4" aria-hidden />
            </Button>

            <Button
              variant="ghost"
              size="icon"
              className="size-8"
              aria-label={`Pular ${session.title}`}
              onClick={() => onSkip(session)}
            >
              <SkipForward className="size-4" aria-hidden />
            </Button>
          </>
        )}

        <Button
          variant="ghost"
          size="icon"
          className="size-8 text-destructive"
          aria-label={`Excluir ${session.title}`}
          onClick={() => onDelete(session)}
        >
          <Trash2 className="size-4" aria-hidden />
        </Button>
      </div>
    </Card>
  );
}

export default function SchedulePage() {
  const [weekStart, setWeekStart] = useState(() => startOfWeek(new Date()));
  const [availabilityOpen, setAvailabilityOpen] = useState(false);
  const [generateOpen, setGenerateOpen] = useState(false);

  const weekEnd = useMemo(() => new Date(weekStart.getTime() + 7 * DAY - 1), [weekStart]);

  const { data: sessions, isLoading } = useStudySessions(weekStart, weekEnd);
  const { data: availability } = useAvailability();
  const { data: summary } = useStudyPlanSummary();

  const completeSession = useCompleteStudySession();
  const skipSession = useSkipStudySession();
  const reopenSession = useReopenStudySession();
  const deleteSession = useDeleteStudySession();

  /** Agrupa por dia para render em colunas/seções. */
  const byDay = useMemo(() => {
    const groups = new Map<string, StudySessionItem[]>();

    for (let offset = 0; offset < 7; offset++) {
      groups.set(new Date(weekStart.getTime() + offset * DAY).toDateString(), []);
    }

    for (const session of sessions ?? []) {
      const key = new Date(session.scheduledStart).toDateString();
      groups.get(key)?.push(session);
    }

    return groups;
  }, [sessions, weekStart]);

  const today = new Date().toDateString();
  const hasAvailability = (availability?.length ?? 0) > 0;
  const weekMinutes = (sessions ?? []).reduce((total, s) => total + s.plannedMinutes, 0);

  return (
    <div className="mx-auto w-full max-w-6xl space-y-5 px-4 py-6 sm:px-6 lg:py-8">
      <div className="flex flex-col items-start justify-between gap-4 sm:flex-row">
        <div className="min-w-0">
          <h1 className="text-xl font-semibold tracking-tight sm:text-2xl">Cronograma</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Blocos de estudo montados a partir das suas provas e atividades.
          </p>
        </div>

        <div className="flex shrink-0 flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={() => setAvailabilityOpen(true)}>
            <Settings2 className="size-4" aria-hidden />
            Disponibilidade
          </Button>

          <Button size="sm" onClick={() => setGenerateOpen(true)}>
            <Sparkles className="size-4" aria-hidden />
            Gerar cronograma
          </Button>
        </div>
      </div>

      {/* Resumo */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="min-w-0 p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs font-medium text-muted-foreground">Blocos planejados</p>
            <CalendarClock className="size-4 text-muted-foreground" aria-hidden />
          </div>
          <p className="mt-2 text-2xl font-semibold tabular-nums">
            {summary?.plannedSessions ?? 0}
          </p>
          <p className="mt-0.5 text-xs text-muted-foreground">de hoje em diante</p>
        </Card>

        <Card className="min-w-0 p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs font-medium text-muted-foreground">Estudado (7 dias)</p>
            <Clock className="size-4 text-muted-foreground" aria-hidden />
          </div>
          <p className="mt-2 text-2xl font-semibold tabular-nums">
            {formatMinutes(summary?.studiedMinutesThisWeek ?? 0)}
          </p>
          <p className="mt-0.5 text-xs text-muted-foreground">tempo real registrado</p>
        </Card>

        <Card className="min-w-0 p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs font-medium text-muted-foreground">Adesão</p>
            <Target className="size-4 text-muted-foreground" aria-hidden />
          </div>
          <p className="mt-2 text-2xl font-semibold tabular-nums">
            {summary?.adherenceRate === null || summary?.adherenceRate === undefined
              ? '—'
              : `${summary.adherenceRate}%`}
          </p>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {summary?.completedSessions ?? 0} concluídos · {summary?.skippedSessions ?? 0} pulados
          </p>
        </Card>

        <Card className="min-w-0 p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="text-xs font-medium text-muted-foreground">Disponível/semana</p>
            <CalendarDays className="size-4 text-muted-foreground" aria-hidden />
          </div>
          <p className="mt-2 text-2xl font-semibold tabular-nums">
            {formatMinutes(summary?.availableMinutesPerWeek ?? 0)}
          </p>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {hasAvailability ? 'que você declarou' : 'nada cadastrado'}
          </p>
        </Card>
      </div>

      {!hasAvailability && (
        <Card className="flex flex-col items-start gap-3 border-status-pending/30 bg-status-pending/5 p-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="min-w-0">
            <p className="text-sm font-medium">Cadastre quando você consegue estudar</p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Sem isso o gerador não tem onde encaixar os blocos.
            </p>
          </div>

          <Button size="sm" className="shrink-0" onClick={() => setAvailabilityOpen(true)}>
            <Settings2 className="size-4" aria-hidden />
            Definir horários
          </Button>
        </Card>
      )}

      {/* Navegação da semana */}
      <div className="flex items-center justify-between gap-3">
        <Button
          variant="outline"
          size="sm"
          onClick={() => setWeekStart(new Date(weekStart.getTime() - 7 * DAY))}
          aria-label="Semana anterior"
        >
          <ChevronLeft className="size-4" aria-hidden />
          <span className="hidden sm:inline">Anterior</span>
        </Button>

        <div className="min-w-0 text-center">
          <p className="truncate text-sm font-medium">
            {formatDate(weekStart)} — {formatDate(weekEnd)}
          </p>
          <p className="text-xs text-muted-foreground">{formatMinutes(weekMinutes)} planejados</p>
        </div>

        <div className="flex shrink-0 gap-2">
          <Button variant="ghost" size="sm" onClick={() => setWeekStart(startOfWeek(new Date()))}>
            Hoje
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={() => setWeekStart(new Date(weekStart.getTime() + 7 * DAY))}
            aria-label="Próxima semana"
          >
            <span className="hidden sm:inline">Próxima</span>
            <ChevronRight className="size-4" aria-hidden />
          </Button>
        </div>
      </div>

      {/* Semana */}
      {isLoading ? (
        <div className="space-y-3">
          {Array.from({ length: 4 }, (_, index) => (
            <Skeleton key={index} className="h-24 rounded-xl" />
          ))}
        </div>
      ) : (sessions?.length ?? 0) === 0 ? (
        <Card>
          <EmptyState
            icon={CalendarClock}
            title="Nenhum bloco nesta semana"
            description={
              hasAvailability
                ? 'Gere o cronograma para preencher a semana com o que está pendente.'
                : 'Defina sua disponibilidade e gere o cronograma.'
            }
            action={
              <Button size="sm" onClick={() => setGenerateOpen(true)}>
                <Sparkles className="size-4" aria-hidden />
                Gerar cronograma
              </Button>
            }
          />
        </Card>
      ) : (
        <div className="space-y-4">
          {[...byDay.entries()].map(([dayKey, daySessions]) => {
            const date = new Date(dayKey);
            const isToday = dayKey === today;

            // Dias vazios só aparecem se houver algo depois: uma sequência de
            // cards vazios no fim da semana é ruído.
            if (daySessions.length === 0) return null;

            const dayMinutes = daySessions.reduce((total, s) => total + s.plannedMinutes, 0);

            return (
              <section key={dayKey} data-testid="day-group">
                <div className="mb-2 flex items-center gap-2">
                  <p className={`text-sm font-medium ${isToday ? 'text-primary' : ''}`}>
                    {WEEKDAY_SHORT_LABELS[date.getDay()]}, {formatDate(date)}
                  </p>

                  {isToday && <Badge>Hoje</Badge>}

                  <span className="text-xs text-muted-foreground">{formatMinutes(dayMinutes)}</span>
                </div>

                <div className="space-y-2">
                  {daySessions.map((session) => (
                    <SessionRow
                      key={session.id}
                      session={session}
                      onComplete={(item) => completeSession.mutate({ id: item.id, data: {} })}
                      onSkip={(item) => skipSession.mutate(item.id)}
                      onReopen={(item) => reopenSession.mutate(item.id)}
                      onDelete={(item) => deleteSession.mutate(item.id)}
                    />
                  ))}
                </div>
              </section>
            );
          })}
        </div>
      )}

      <AvailabilityDialog
        open={availabilityOpen}
        onOpenChange={setAvailabilityOpen}
        windows={availability ?? []}
      />

      <GeneratePlanDialog
        open={generateOpen}
        onOpenChange={setGenerateOpen}
        hasAvailability={hasAvailability}
        onGenerated={(firstBlockDate) => {
          // Leva o usuário até onde os blocos foram parar. Gerando num domingo,
          // tudo cai na semana seguinte — e a semana atual ficaria vazia.
          if (firstBlockDate) setWeekStart(startOfWeek(firstBlockDate));
        }}
      />
    </div>
  );
}
