'use client';

import { useState } from 'react';
import { AlertTriangle, Loader2, Sparkles } from 'lucide-react';
import type { GeneratePlanResult } from '@painel/shared';
import { useGeneratePlan } from '@/hooks/use-study-plan';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FormField } from '@/components/ui/form-field';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

interface GeneratePlanDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  hasAvailability: boolean;
  /**
   * Data do primeiro bloco criado.
   *
   * A tela usa isso para navegar ate a semana do resultado: gerando num
   * domingo, todos os blocos caem na semana seguinte, e sem isso o usuario le
   * "9 blocos criados" e continua olhando uma semana vazia.
   */
  onGenerated: (firstBlockDate: Date | null) => void;
}

/**
 * Configuracao e disparo da geracao.
 *
 * Depois de gerar, o dialogo NAO fecha sozinho: mostra o que foi criado e,
 * principalmente, o que nao coube. Fechar direto esconderia justamente a
 * informacao que o aluno precisa para ajustar a disponibilidade.
 */
export function GeneratePlanDialog({
  open,
  onOpenChange,
  hasAvailability,
  onGenerated,
}: GeneratePlanDialogProps) {
  const [days, setDays] = useState(7);
  const [blockMinutes, setBlockMinutes] = useState(50);
  const [breakMinutes, setBreakMinutes] = useState(10);
  const [maxBlocksPerDay, setMaxBlocksPerDay] = useState(4);
  const [result, setResult] = useState<GeneratePlanResult | null>(null);

  const generatePlan = useGeneratePlan();

  const handleGenerate = async (): Promise<void> => {
    try {
      const generated = await generatePlan.mutateAsync({
        days,
        blockMinutes,
        breakMinutes,
        maxBlocksPerDay,
      });

      setResult(generated);

      const first = generated.sessions
        .filter((session) => session.autoGenerated)
        .map((session) => new Date(session.scheduledStart))
        .sort((a, b) => a.getTime() - b.getTime())[0];

      onGenerated(first ?? null);
    } catch {
      // O toast de erro vem do hook.
    }
  };

  const close = (): void => {
    setResult(null);
    onOpenChange(false);
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next) setResult(null);
        onOpenChange(next);
      }}
    >
      <DialogContent className="max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Gerar cronograma</DialogTitle>
          <DialogDescription>
            Os blocos saem das provas e atividades já cadastradas, encaixados na sua
            disponibilidade.
          </DialogDescription>
        </DialogHeader>

        {!hasAvailability && (
          <div className="flex items-start gap-2 rounded-lg border border-status-pending/30 bg-status-pending/10 p-3">
            <AlertTriangle className="mt-0.5 size-4 shrink-0 text-status-pending" aria-hidden />
            <p className="text-sm">
              Cadastre sua disponibilidade primeiro — sem ela o gerador não tem onde encaixar os
              blocos.
            </p>
          </div>
        )}

        {result === null ? (
          <div className="grid gap-4 sm:grid-cols-2">
            <FormField label="Planejar os próximos" hint="dias">
              {(field) => (
                <Input
                  id={field.id}
                  type="number"
                  min={1}
                  max={28}
                  value={days}
                  onChange={(event) => setDays(Number(event.target.value))}
                />
              )}
            </FormField>

            <FormField label="Duração do bloco" hint="minutos">
              {(field) => (
                <Input
                  id={field.id}
                  type="number"
                  min={15}
                  max={240}
                  step={5}
                  value={blockMinutes}
                  onChange={(event) => setBlockMinutes(Number(event.target.value))}
                />
              )}
            </FormField>

            <FormField label="Intervalo entre blocos" hint="minutos">
              {(field) => (
                <Input
                  id={field.id}
                  type="number"
                  min={0}
                  max={60}
                  step={5}
                  value={breakMinutes}
                  onChange={(event) => setBreakMinutes(Number(event.target.value))}
                />
              )}
            </FormField>

            <FormField label="Máximo por dia" hint="blocos">
              {(field) => (
                <Input
                  id={field.id}
                  type="number"
                  min={1}
                  max={12}
                  value={maxBlocksPerDay}
                  onChange={(event) => setMaxBlocksPerDay(Number(event.target.value))}
                />
              )}
            </FormField>
          </div>
        ) : (
          <div className="space-y-3" data-testid="generate-result">
            <div className="flex flex-wrap gap-2">
              <Badge variant="completed">{result.created} blocos criados</Badge>

              {result.preserved > 0 && (
                <Badge variant="secondary">{result.preserved} seus preservados</Badge>
              )}

              {result.replaced > 0 && (
                <Badge variant="outline">{result.replaced} automáticos substituídos</Badge>
              )}
            </div>

            {result.unscheduled.length > 0 && (
              <div className="space-y-2">
                <p className="text-sm font-medium">Não coube no período</p>

                <ul className="max-h-48 space-y-1.5 overflow-y-auto">
                  {result.unscheduled.map((item, index) => (
                    <li key={index} className="rounded-md border bg-muted/40 px-2.5 py-2">
                      <p className="truncate text-sm">{item.title}</p>
                      <p className="text-xs text-muted-foreground">{item.reason}</p>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {result.created > 0 && result.unscheduled.length === 0 && (
              <p className="text-sm text-muted-foreground">
                Tudo o que estava pendente coube no seu tempo disponível.
              </p>
            )}
          </div>
        )}

        <p className="text-xs text-muted-foreground">
          Blocos que você criou ou já concluiu não são alterados — a geração substitui apenas os
          automáticos ainda planejados.
        </p>

        <DialogFooter>
          <Button variant="outline" onClick={close}>
            {result === null ? 'Cancelar' : 'Fechar'}
          </Button>

          {result === null && (
            <Button onClick={() => void handleGenerate()} disabled={generatePlan.isPending}>
              {generatePlan.isPending ? (
                <Loader2 className="size-4 animate-spin" aria-hidden />
              ) : (
                <Sparkles className="size-4" aria-hidden />
              )}
              Gerar
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
