import type {
  AvailabilityWindow,
  CompleteStudySessionInput,
  CreateStudySessionInput,
  GeneratePlanInput,
  GeneratePlanResult,
  QuickStartStudySessionInput,
  SaveAvailabilityInput,
  StudyPlanSummary,
  StudySessionItem,
  UpdateStudySessionInput,
} from '@painel/shared';
import { prisma, type Prisma } from '../config/prisma.js';
import {
  availabilityRepository,
  studySessionRepository,
  type AvailabilityRow,
  type StudySessionRow,
} from '../repositories/study-plan.repository.js';
import { subjectRepository } from '../repositories/subject.repository.js';
import { assignmentRepository } from '../repositories/assignment.repository.js';
import { examRepository } from '../repositories/exam.repository.js';
import { examPrepRepository } from '../repositories/exam-prep.repository.js';
import { AppError } from '../utils/app-error.js';
import {
  desiredBlocksFor,
  generateSchedule,
  type BusyInterval,
  type StudyTarget,
} from '../utils/schedule-generator.js';
import { emptyToNull } from '../utils/text.js';

/** Regra de negocio do cronograma. */

const MS_PER_DAY = 24 * 60 * 60 * 1000;

function toSessionItem(row: StudySessionRow): StudySessionItem {
  return {
    id: row.id,
    title: row.title,
    scheduledStart: row.scheduledStart.toISOString(),
    scheduledEnd: row.scheduledEnd.toISOString(),
    plannedMinutes: Math.round((row.scheduledEnd.getTime() - row.scheduledStart.getTime()) / 60000),
    actualMinutes: row.actualMinutes,
    status: row.status,
    notes: row.notes,
    autoGenerated: row.autoGenerated,
    subject: row.subject,
    assignment: row.assignment,
    exam: row.exam,
    examPrepId: row.examPrepId,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

function toAvailabilityWindow(row: AvailabilityRow): AvailabilityWindow {
  return {
    id: row.id,
    dayOfWeek: row.dayOfWeek,
    startMinute: row.startMinute,
    endMinute: row.endMinute,
  };
}

/** Vinculos do bloco, validados contra o dono. */
interface ResolvedLinks {
  subjectId: string | null;
  assignmentId: string | null;
  examId: string | null;
}

async function resolveLinks(
  userId: string,
  input: { subjectId?: string; assignmentId?: string; examId?: string },
): Promise<ResolvedLinks> {
  const subjectId = emptyToNull(input.subjectId);
  const assignmentId = emptyToNull(input.assignmentId);
  const examId = emptyToNull(input.examId);

  if (subjectId && !(await subjectRepository.findById(userId, subjectId))) {
    throw AppError.badRequest('Disciplina inválida');
  }

  if (assignmentId && !(await assignmentRepository.findById(userId, assignmentId))) {
    throw AppError.badRequest('Atividade inválida');
  }

  if (examId && !(await examRepository.findById(userId, examId))) {
    throw AppError.badRequest('Prova inválida');
  }

  return { subjectId, assignmentId, examId };
}

/**
 * Sobreposicao de janelas no mesmo dia.
 *
 * Duas janelas sobrepostas fariam o gerador contar o mesmo tempo duas vezes e
 * marcar dois blocos no mesmo horario. Barrar na entrada e mais barato que
 * deduplicar depois.
 */
function assertNoOverlap(windows: SaveAvailabilityInput['windows']): void {
  const byDay = new Map<number, { startMinute: number; endMinute: number }[]>();

  for (const window of windows) {
    const existing = byDay.get(window.dayOfWeek) ?? [];

    if (
      existing.some(
        (other) => window.startMinute < other.endMinute && other.startMinute < window.endMinute,
      )
    ) {
      throw AppError.badRequest('Há janelas de disponibilidade sobrepostas no mesmo dia');
    }

    existing.push(window);
    byDay.set(window.dayOfWeek, existing);
  }
}

export const studyPlanService = {
  // --- Disponibilidade -------------------------------------------------------

  async getAvailability(userId: string): Promise<AvailabilityWindow[]> {
    const rows = await availabilityRepository.findMany(userId);

    return rows.map(toAvailabilityWindow);
  },

  async saveAvailability(
    userId: string,
    input: SaveAvailabilityInput,
  ): Promise<AvailabilityWindow[]> {
    assertNoOverlap(input.windows);

    const rows = await availabilityRepository.replaceAll(userId, input.windows);

    return rows.map(toAvailabilityWindow);
  },

  // --- Blocos -----------------------------------------------------------------

  async list(userId: string, from: Date, to: Date): Promise<StudySessionItem[]> {
    const rows = await studySessionRepository.findBetween(userId, from, to);

    return rows.map(toSessionItem);
  },

  async create(userId: string, input: CreateStudySessionInput): Promise<StudySessionItem> {
    const links = await resolveLinks(userId, input);

    const row = await studySessionRepository.create(userId, {
      title: input.title,
      scheduledStart: input.scheduledStart,
      scheduledEnd: input.scheduledEnd,
      notes: emptyToNull(input.notes),
      // Criado a mao: a regeneracao do cronograma nunca vai apagar este bloco.
      autoGenerated: false,
      ...links,
    });

    return toSessionItem(row);
  },

  /**
   * "Começar sessão" (Etapa 9): dispara um bloco `IN_PROGRESS` agora, com
   * título e disciplina herdados da prova - nada digitado de novo. É a mesma
   * máquina de estados do Cronograma, só que entrando por "agora" em vez de
   * um agendamento futuro.
   */
  async quickStart(userId: string, input: QuickStartStudySessionInput): Promise<StudySessionItem> {
    const plan = await examPrepRepository.findExamRefById(userId, input.examPrepId);

    if (!plan) throw AppError.notFound('Plano de estudos');

    const now = new Date();

    const row = await studySessionRepository.create(userId, {
      title: `Sessão de estudo — ${plan.exam.title}`,
      scheduledStart: now,
      scheduledEnd: now,
      status: 'IN_PROGRESS',
      autoGenerated: false,
      subjectId: plan.exam.subjectId,
      examPrepId: plan.id,
    });

    return toSessionItem(row);
  },

  async update(
    userId: string,
    id: string,
    input: UpdateStudySessionInput,
  ): Promise<StudySessionItem> {
    const data: Prisma.StudySessionUncheckedUpdateInput = {};

    if (input.title !== undefined) data.title = input.title;
    if (input.scheduledStart !== undefined) data.scheduledStart = input.scheduledStart;
    if (input.scheduledEnd !== undefined) data.scheduledEnd = input.scheduledEnd;
    if (input.notes !== undefined) data.notes = emptyToNull(input.notes);

    const touchesLinks =
      input.subjectId !== undefined ||
      input.assignmentId !== undefined ||
      input.examId !== undefined;

    if (touchesLinks) Object.assign(data, await resolveLinks(userId, input));

    // Editar um bloco gerado o torna do usuario: ele deixa de ser descartavel
    // pela proxima geracao, senao o ajuste manual sumiria sem aviso.
    if (Object.keys(data).length > 0) data.autoGenerated = false;

    if (input.scheduledStart !== undefined || input.scheduledEnd !== undefined) {
      const current = await studySessionRepository.findById(userId, id);

      if (!current) throw AppError.notFound('Bloco de estudo');

      const start = input.scheduledStart ?? current.scheduledStart;
      const end = input.scheduledEnd ?? current.scheduledEnd;

      if (end <= start) throw AppError.badRequest('O fim precisa ser depois do início');
    }

    const row = await studySessionRepository.update(userId, id, data);

    if (!row) throw AppError.notFound('Bloco de estudo');

    return toSessionItem(row);
  },

  /**
   * Marca o bloco como concluido.
   *
   * `actualMinutes` separa o planejado do executado: sem ele, "estudei 6 horas
   * esta semana" seria uma intencao, nao um fato. Quando o aluno nao informa:
   * um bloco `PLANNED` (agendado de antemao, fluxo normal do Cronograma)
   * assume a duracao planejada - a melhor estimativa disponivel. Um bloco
   * `IN_PROGRESS` (nascido de "Começar sessão", Etapa 9) nao tem duracao
   * planejada de verdade - os dois horarios nascem iguais -, entao o padrao
   * vira o tempo real decorrido desde o inicio, calculado no servidor (nunca
   * confiando so no cronometro do cliente).
   */
  async complete(
    userId: string,
    id: string,
    input: CompleteStudySessionInput,
  ): Promise<StudySessionItem> {
    const current = await studySessionRepository.findById(userId, id);

    if (!current) throw AppError.notFound('Bloco de estudo');

    const now = new Date();
    const isQuickSession = current.status === 'IN_PROGRESS';

    const defaultMinutes = isQuickSession
      ? Math.max(0, Math.round((now.getTime() - current.scheduledStart.getTime()) / 60000))
      : Math.round((current.scheduledEnd.getTime() - current.scheduledStart.getTime()) / 60000);

    const row = await studySessionRepository.update(userId, id, {
      status: 'COMPLETED',
      actualMinutes: input.actualMinutes ?? defaultMinutes,
      // A sessão rápida nasce com scheduledEnd == scheduledStart; fechar o
      // intervalo real agora faz o bloco aparecer com duração de verdade no
      // Cronograma, em vez de um bloco de tamanho zero.
      ...(isQuickSession ? { scheduledEnd: now } : {}),
      ...(input.notes !== undefined ? { notes: emptyToNull(input.notes) } : {}),
    });

    if (!row) throw AppError.notFound('Bloco de estudo');

    return toSessionItem(row);
  },

  async skip(userId: string, id: string): Promise<StudySessionItem> {
    const row = await studySessionRepository.update(userId, id, {
      status: 'SKIPPED',
      actualMinutes: null,
    });

    if (!row) throw AppError.notFound('Bloco de estudo');

    return toSessionItem(row);
  },

  /** Volta o bloco para planejado, desfazendo conclusao ou pulo. */
  async reopen(userId: string, id: string): Promise<StudySessionItem> {
    const row = await studySessionRepository.update(userId, id, {
      status: 'PLANNED',
      actualMinutes: null,
    });

    if (!row) throw AppError.notFound('Bloco de estudo');

    return toSessionItem(row);
  },

  async remove(userId: string, id: string): Promise<void> {
    const deleted = await studySessionRepository.delete(userId, id);

    if (!deleted) throw AppError.notFound('Bloco de estudo');
  },

  // --- Geracao -------------------------------------------------------------------

  /**
   * Monta os alvos a partir do que ja existe no sistema.
   *
   * O cronograma nao pede ao aluno que redigite o que estudar: provas e
   * atividades ja estao cadastradas, e e delas que sai o plano.
   */
  async collectTargets(userId: string, now: Date, horizon: Date): Promise<StudyTarget[]> {
    const [assignments, exams] = await Promise.all([
      prisma.assignment.findMany({
        where: {
          userId,
          status: { in: ['PENDING', 'IN_PROGRESS'] },
          dueDate: { gte: now, lte: horizon },
        },
        select: {
          id: true,
          title: true,
          dueDate: true,
          priority: true,
          subject: { select: { id: true, name: true } },
        },
      }),
      prisma.exam.findMany({
        // Provas entram com folga alem do horizonte: comecar a estudar duas
        // semanas antes e justamente o que a repeticao distribuida pede.
        where: { userId, date: { gte: now, lte: new Date(horizon.getTime() + 21 * MS_PER_DAY) } },
        select: {
          id: true,
          title: true,
          date: true,
          // O peso da prova e o do componente que ela representa (Etapa 18).
          gradeComponent: { select: { weight: true } },
          subject: { select: { id: true, name: true } },
        },
      }),
    ]);

    const targets: StudyTarget[] = [];

    for (const exam of exams) {
      targets.push({
        id: exam.id,
        kind: 'EXAM',
        title: exam.title,
        subjectId: exam.subject?.id ?? null,
        subjectName: exam.subject?.name ?? null,
        dueDate: exam.date,
        priority: null,
        weight: exam.gradeComponent?.weight ?? null,
        desiredBlocks: desiredBlocksFor('EXAM', exam.date, now),
      });
    }

    for (const assignment of assignments) {
      targets.push({
        id: assignment.id,
        kind: 'ASSIGNMENT',
        title: assignment.title,
        subjectId: assignment.subject?.id ?? null,
        subjectName: assignment.subject?.name ?? null,
        dueDate: assignment.dueDate,
        priority: assignment.priority,
        weight: null,
        desiredBlocks: desiredBlocksFor('ASSIGNMENT', assignment.dueDate, now),
      });
    }

    return targets;
  },

  /**
   * Gera o cronograma.
   *
   * Substitui apenas os blocos automaticos ainda planejados no horizonte. O
   * que o aluno criou ou ja executou permanece, e vira obstaculo que o gerador
   * desvia - marcar estudo em cima de um compromisso existente seria pior que
   * nao marcar nada.
   */
  async generate(userId: string, input: GeneratePlanInput): Promise<GeneratePlanResult> {
    const now = new Date();
    const horizon = new Date(now.getTime() + input.days * MS_PER_DAY);

    const [windows, targets, manual, exams] = await Promise.all([
      availabilityRepository.findMany(userId),
      this.collectTargets(userId, now, horizon),
      studySessionRepository.findManualBetween(userId, now, horizon),
      prisma.exam.findMany({
        where: { userId, date: { gte: now, lte: horizon } },
        select: { date: true, durationMinutes: true },
      }),
    ]);

    const busy: BusyInterval[] = [
      ...manual.map((session) => ({ start: session.scheduledStart, end: session.scheduledEnd })),
      // A propria prova ocupa a agenda: nao faz sentido marcar estudo no
      // horario em que o aluno estara fazendo a prova.
      ...exams.map((exam) => ({
        start: exam.date,
        end: new Date(exam.date.getTime() + (exam.durationMinutes ?? 120) * 60000),
      })),
    ];

    const result = generateSchedule(
      targets,
      windows.map((window) => ({
        dayOfWeek: window.dayOfWeek,
        startMinute: window.startMinute,
        endMinute: window.endMinute,
      })),
      busy,
      {
        days: input.days,
        blockMinutes: input.blockMinutes,
        breakMinutes: input.breakMinutes,
        maxBlocksPerDay: input.maxBlocksPerDay,
      },
      now,
    );

    // Provas que já têm Plano de Estudos (Etapa 27) - as sessões geradas a
    // partir delas já saem com `examPrepId` preenchido, sem passo extra.
    const examIds = [
      ...new Set(result.blocks.map((block) => block.examId).filter((id) => id !== null)),
    ];
    const examPrepByExamId = await examPrepRepository.mapIdsByExamIds(userId, examIds);

    const { removed } = await studySessionRepository.replaceGenerated(
      userId,
      now,
      horizon,
      result.blocks.map((block) => ({
        title: block.title,
        scheduledStart: block.start,
        scheduledEnd: block.end,
        subjectId: block.subjectId,
        assignmentId: block.assignmentId,
        examId: block.examId,
        examPrepId: block.examId ? (examPrepByExamId.get(block.examId) ?? null) : null,
      })),
    );

    const sessions = await studySessionRepository.findBetween(userId, now, horizon);

    return {
      created: result.blocks.length,
      replaced: removed,
      preserved: manual.length,
      unscheduled: result.unscheduled,
      sessions: sessions.map(toSessionItem),
    };
  },

  async summary(userId: string): Promise<StudyPlanSummary> {
    const now = new Date();

    const [stats, windows] = await Promise.all([
      studySessionRepository.summarize(
        userId,
        now,
        new Date(now.getTime() - 7 * MS_PER_DAY),
        new Date(now.getTime() + 7 * MS_PER_DAY),
      ),
      availabilityRepository.findMany(userId),
    ]);

    const decided = stats.completed + stats.skipped;

    return {
      plannedSessions: stats.plannedSessions,
      plannedMinutesThisWeek: stats.plannedMinutes,
      studiedMinutesThisWeek: stats.studiedMinutes,
      completedSessions: stats.completed,
      skippedSessions: stats.skipped,
      adherenceRate: decided === 0 ? null : Math.round((stats.completed / decided) * 100),
      availableMinutesPerWeek: windows.reduce(
        (total, window) => total + (window.endMinute - window.startMinute),
        0,
      ),
    };
  },
};
