import { prisma, type Prisma } from '../config/prisma.js';

/** Acesso a dados do cronograma: disponibilidade e blocos de estudo. */

// ---------------------------------------------------------------------------
// Disponibilidade
// ---------------------------------------------------------------------------

const availabilitySelect = {
  id: true,
  dayOfWeek: true,
  startMinute: true,
  endMinute: true,
} satisfies Prisma.StudyAvailabilitySelect;

export type AvailabilityRow = Prisma.StudyAvailabilityGetPayload<{
  select: typeof availabilitySelect;
}>;

export const availabilityRepository = {
  findMany(userId: string): Promise<AvailabilityRow[]> {
    return prisma.studyAvailability.findMany({
      where: { userId },
      select: availabilitySelect,
      orderBy: [{ dayOfWeek: 'asc' }, { startMinute: 'asc' }],
    });
  },

  /**
   * Substitui a disponibilidade inteira.
   *
   * Apagar e recriar dentro de uma transacao e mais simples e mais seguro que
   * um diff janela a janela: o cliente envia a grade completa, e um erro no
   * meio nao deixa metade da semana atualizada.
   */
  async replaceAll(
    userId: string,
    windows: { dayOfWeek: number; startMinute: number; endMinute: number }[],
  ): Promise<AvailabilityRow[]> {
    await prisma.$transaction([
      prisma.studyAvailability.deleteMany({ where: { userId } }),
      prisma.studyAvailability.createMany({
        data: windows.map((window) => ({ ...window, userId })),
      }),
    ]);

    return this.findMany(userId);
  },
};

// ---------------------------------------------------------------------------
// Blocos de estudo
// ---------------------------------------------------------------------------

const sessionSelect = {
  id: true,
  title: true,
  scheduledStart: true,
  scheduledEnd: true,
  actualMinutes: true,
  status: true,
  notes: true,
  autoGenerated: true,
  createdAt: true,
  updatedAt: true,
  subject: { select: { id: true, name: true, color: true } },
  assignment: { select: { id: true, title: true } },
  exam: { select: { id: true, title: true } },
} satisfies Prisma.StudySessionSelect;

export type StudySessionRow = Prisma.StudySessionGetPayload<{ select: typeof sessionSelect }>;

export const studySessionRepository = {
  findBetween(userId: string, from: Date, to: Date): Promise<StudySessionRow[]> {
    return prisma.studySession.findMany({
      where: { userId, scheduledStart: { gte: from, lte: to } },
      select: sessionSelect,
      orderBy: { scheduledStart: 'asc' },
    });
  },

  findById(userId: string, id: string): Promise<StudySessionRow | null> {
    return prisma.studySession.findFirst({ where: { id, userId }, select: sessionSelect });
  },

  create(
    userId: string,
    data: Omit<Prisma.StudySessionUncheckedCreateInput, 'userId'>,
  ): Promise<StudySessionRow> {
    return prisma.studySession.create({ data: { ...data, userId }, select: sessionSelect });
  },

  async update(
    userId: string,
    id: string,
    data: Prisma.StudySessionUncheckedUpdateInput,
  ): Promise<StudySessionRow | null> {
    const result = await prisma.studySession.updateMany({ where: { id, userId }, data });

    if (result.count === 0) return null;

    return this.findById(userId, id);
  },

  async delete(userId: string, id: string): Promise<boolean> {
    const result = await prisma.studySession.deleteMany({ where: { id, userId } });

    return result.count > 0;
  },

  /**
   * Substitui os blocos automaticos futuros.
   *
   * O recorte e deliberadamente estreito: `autoGenerated: true`, ainda
   * `PLANNED` e no futuro. Blocos manuais, ja concluidos ou passados sao
   * historico de estudo real - regerar o cronograma nao pode apaga-los.
   */
  async replaceGenerated(
    userId: string,
    now: Date,
    horizon: Date,
    blocks: Omit<Prisma.StudySessionUncheckedCreateInput, 'userId'>[],
  ): Promise<{ removed: number; created: number }> {
    const [removed] = await prisma.$transaction([
      prisma.studySession.deleteMany({
        where: {
          userId,
          autoGenerated: true,
          status: 'PLANNED',
          scheduledStart: { gte: now, lte: horizon },
        },
      }),
      prisma.studySession.createMany({
        data: blocks.map((block) => ({ ...block, userId, autoGenerated: true })),
      }),
    ]);

    return { removed: removed.count, created: blocks.length };
  },

  /** Blocos manuais no horizonte: o gerador desvia deles em vez de sobrepor. */
  findManualBetween(userId: string, from: Date, to: Date): Promise<StudySessionRow[]> {
    return prisma.studySession.findMany({
      where: {
        userId,
        scheduledStart: { gte: from, lte: to },
        OR: [{ autoGenerated: false }, { status: { not: 'PLANNED' } }],
      },
      select: sessionSelect,
      orderBy: { scheduledStart: 'asc' },
    });
  },

  async summarize(
    userId: string,
    now: Date,
    weekAgo: Date,
    weekAhead: Date,
  ): Promise<{
    plannedSessions: number;
    plannedMinutes: number;
    studiedMinutes: number;
    completed: number;
    skipped: number;
  }> {
    const [planned, upcoming, studied, completed, skipped] = await prisma.$transaction([
      prisma.studySession.count({
        where: { userId, status: 'PLANNED', scheduledStart: { gte: now } },
      }),
      prisma.studySession.findMany({
        where: { userId, scheduledStart: { gte: now, lte: weekAhead } },
        select: { scheduledStart: true, scheduledEnd: true },
      }),
      prisma.studySession.aggregate({
        where: { userId, status: 'COMPLETED', scheduledStart: { gte: weekAgo } },
        _sum: { actualMinutes: true },
      }),
      prisma.studySession.count({ where: { userId, status: 'COMPLETED' } }),
      prisma.studySession.count({ where: { userId, status: 'SKIPPED' } }),
    ]);

    const plannedMinutes = upcoming.reduce(
      (total, session) =>
        total + (session.scheduledEnd.getTime() - session.scheduledStart.getTime()) / 60000,
      0,
    );

    return {
      plannedSessions: planned,
      plannedMinutes: Math.round(plannedMinutes),
      studiedMinutes: studied._sum.actualMinutes ?? 0,
      completed,
      skipped,
    };
  },
};
